# Site settings
title: WebRTC
email: webmaster@webrtc.org
description: "WebRTC is a free, open project that enables web browsers with Real-Time Communications (RTC) capabilities via simple JavaScript APIs. The WebRTC components have been optimized to best serve this purpose."
baseurl: "/webrtc-org"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title.html
# relative_permalinks: true

exclude: [vendor]
